### ISSUE TITLE
Rename the go module to github.com/ocp-power-automation/rsct-operator

### ISSUE THREAD

**Issue by mkumatag** [ocp-power-automation/rsct-operator#5]
RIghtnow it is 
https://github.com/ocp-power-automation/rsct-operator/blob/8d568fee264c564d4490dda9eadc777ceb00d1a3/go.mod#L1

Needs update to github.com/ocp-power-automation/rsct-operator

**Comment by varad-ahirwadkar** [comment]
PR: https://github.com/ocp-power-automation/rsct-operator/pull/7
